### ISSUE TITLE
Theme not compatible with latest VS Code 1.65.2

### ISSUE THREAD

**Issue by NuttySouth** [taelid/summer-theme-vscode#1]
While trying to install the theme, an error indicating it not compatible with the current version of VS Code 1.65.2

**Comment by taelid** [comment]
Thanks for bringing to my attention! I've updated the VS Code version requirements from **'1.66.0 and above' to '1.55.0 and above'**. Error should be fixed as of summer theme v0.2.9, please let me know if there's still an issue.
