### ISSUE TITLE
Suggestion box is transparent and unreadable

### ISSUE THREAD

**Issue by zivkaplan** [taelid/summer-theme-vscode#2]
Hi, 
thanks for your theme.

One thing to improve - the sujjestion bix background is transparent, making it unreadable if there is any text behind. 
See below (sorry for the bad screenshot)

![photo_2022-04-12_08-36-05](https://user-images.githubusercontent.com/80772683/162888390-fe6c9d9c-c41a-4501-a6d8-04c888fc2905.jpg)

**Comment by taelid** [comment]
Thanks for using my theme! 

That should definitely not be happening, I've pushed a quick update with **v0.3.0** to fix the transparency on tooltips.
